version: '3.1'

services: 
  db:
    image: postgres:alpine
    container_name: msmf_db
    env_file: .env
    ports:
      - 5432:5432
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: msmf_dev
    env_file: .env
    ports: 
      - 8080:3000
    depends_on:
      - db
    volumes: 
      - ./src:/srv/website/src
      - ./bin:/srv/website/bin
      - ./static:/srv/website/static