version: '3.1'

services:
  db:
    image: postgres:alpine
    container_name: msmf_db
    env_file: .env
    ports:
      - 5432:5432
  web:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: msmf_dev
    env_file: .env
    ports:
      - 8080:3000
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/src:/srv/website/src:ro
      - static:/srv/website/static
#  react:
#    image: gradle:6.8-jdk15
#    command: ["gradle", "browserDevelopmentWebpack", "--continuous"]
##    command: ["ls"]
#    volumes:
#      - ./frontend:/home/gradle/
#      - static:/home/gradle/build/developmentExecutable
  react:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src:ro
      - static:/app/dist

volumes:
  static:
