version: '3.1'

services: 
  db:
    image: postgres:alpine
    container_name: msmf_db
    env_file: .env
    ports:
      - 5432:5432
  web:
    build: .
    container_name: msmf
    env_file: .env
    ports: 
      - 80:5000
    depends_on:
      - db
    volumes:
      - ./certs:/srv/website/certs:ro